version: '2.1'

services:
  pipenv:
    environment:
      - http_proxy
      - https_proxy
    image: registry.gitlab.com/rconan/docker-pipenv:2018.11.29-0
    command: lock
    volumes:
      - ${PWD:-.}:/code
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:2.40.1-0
    volumes:
      - ${PWD:-.}:/files
  jshint:
    image: registry.gitlab.com/rconan/docker-jshint:2.9.6-0
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:3.5.0-4
    volumes:
      - ${PWD:-.}:/code
  webpack:
    build:
      context: .
      dockerfile: webpack/Dockerfile
      args:
        webpack_tag: 4.23.1-1
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/webpack}
