version: '2.1'

services:
  db:
    image: postgres:9.6.10-alpine
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      - H2_DEBUG
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.nginx
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  web:
    build: ./nginx
    depends_on:
      - app
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
    ports:
      - "8080:80"
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
