version: '2.1'

services:
  jshint:
    image: registry.gitlab.com/rconan/docker-jshint:0.0.3
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:0.0.3
    volumes:
      - ${PWD:-.}:/code
