version: '2.1'

services:
  db:
    image: postgres:9.6.10-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
       context: .
       args:
          DEVELOPMENT: "true"
    command: runserver 0.0.0.0:3031
    depends_on:
      - db
    environment:
      - H2_DEBUG=True
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.development
      - H2_SILK
    image: ${IMAGE_TAG:-hunter2_app}
    ports:
      - "${H2_LISTEN:-127.0.0.1:8080}:3031"
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - static:/static
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
    tty: true

volumes:
  db: {}
  config: {}
  static: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
